import type { StoredRunbookChunk } from "./runbook-retriever";

// Deliberately small, hand-written, and committed in-source — no ingestion
// pipeline, no vector store (see docs §15 vs. this vertical slice's explicit
// out-of-scope list). chunkId values are stable, human-readable, and
// OpsPilot-controlled; never generated. Covers the four required topics plus
// one intentionally irrelevant control topic.
export const RUNBOOK_CORPUS: readonly StoredRunbookChunk[] = [
  {
    chunkId: "runbook-notification-degradation-001",
    runbookId: "notification-service-runbook",
    title: "Notification Service Degradation",
    content:
      "The notification-service reports a DEGRADED status when downstream email or push " +
      "delivery providers are slow to acknowledge requests. Symptoms include delayed " +
      "notification emails and a rising queue depth on the notification worker. Confirm " +
      "the service status via get_service_status before escalating.",
    serviceSlug: "notification-service",
    category: "SERVICE_DEGRADATION",
  },
  {
    chunkId: "runbook-notification-queue-backlog-001",
    runbookId: "notification-queue-runbook",
    title: "Notification Queue Backlog — Symptoms",
    content:
      "A growing backlog in the notification queue presents as customers reporting delayed " +
      "emails or push notifications, even when the notification-service itself reports " +
      "OPERATIONAL. Backlogs typically follow a burst of ticket-related notifications or a " +
      "slow downstream provider.",
    serviceSlug: "notification-service",
    category: "SERVICE_DEGRADATION",
  },
  {
    chunkId: "runbook-notification-queue-backlog-002",
    runbookId: "notification-queue-runbook",
    title: "Notification Queue Backlog — Remediation Steps",
    content:
      "To remediate a notification queue backlog: verify downstream provider status, scale " +
      "the notification worker pool if CPU-bound, and communicate expected delivery delays " +
      "to affected customers. Do not purge the queue without confirming duplicate " +
      "notifications are acceptable.",
    serviceSlug: "notification-service",
    category: "SERVICE_DEGRADATION",
  },
  {
    chunkId: "runbook-auth-failures-001",
    runbookId: "auth-failures-runbook",
    title: "Authentication Failures — Symptoms",
    content:
      "Authentication failures present as customers unable to log in, elevated 401 responses " +
      "from auth-service, or repeated password-reset requests. Check auth-service status and " +
      "recent deploys before assuming a customer-side credential issue.",
    serviceSlug: "auth-service",
    category: "AUTHENTICATION",
  },
  {
    chunkId: "runbook-auth-failures-002",
    runbookId: "auth-failures-runbook",
    title: "Authentication Failures — Root Causes",
    content:
      "Common root causes of authentication failures include an expired signing key, a " +
      "misconfigured identity provider integration, or clock drift on auth-service hosts " +
      "invalidating time-based tokens. Correlate with the most recent auth-service deploy " +
      "timestamp.",
    serviceSlug: "auth-service",
    category: "AUTHENTICATION",
  },
  {
    chunkId: "runbook-database-connection-saturation-001",
    runbookId: "database-runbook",
    title: "Database Connection Pool Saturation",
    content:
      "Connection pool saturation presents as intermittent timeouts across multiple services " +
      "sharing the same database. Check active connection count against the configured pool " +
      "size; a sudden spike in long-running queries or a leaked connection from a recent " +
      "deploy are the most common causes.",
    serviceSlug: "database",
    category: "CONFIGURATION",
  },
  {
    chunkId: "runbook-billing-invoice-formatting-001",
    runbookId: "billing-runbook",
    title: "Billing Invoice PDF Formatting",
    content:
      "Invoice PDFs are generated by the billing-service export pipeline. Formatting issues " +
      "(misaligned totals, missing line items) are almost always caused by a template " +
      "version mismatch after a billing-service deploy, unrelated to notification, " +
      "authentication, or database issues.",
    serviceSlug: "billing-service",
    category: "DATA_QUALITY",
  },
];

const duplicateChunkIds = RUNBOOK_CORPUS.map((chunk) => chunk.chunkId).filter(
  (chunkId, index, all) => all.indexOf(chunkId) !== index,
);
if (duplicateChunkIds.length > 0) {
  throw new Error(
    `RUNBOOK_CORPUS contains duplicate chunkId(s): ${[...new Set(duplicateChunkIds)].join(", ")}`,
  );
}
